### ISSUE TITLE
E2E and Integration tests

### ISSUE THREAD

**Issue by mustafasalfiti** [openwallet-foundation-labs/credhub#50]
E2E and Integration test to make sure that, the system still works after a pull request to main

**Comment by cre8** [comment]
Instead of mocking services, we can start the backend services as docker containers and perform the tests. This approach would allow us to check the coverage for the frontends. For the backends we can start them as nodejs process to calculate the coverage

We can import a realm in keycloak with a pre configured client for the issuer and verifier authorization.

**Comment by cre8** [comment]
I already added the setup with Testcontainers and a test for the settings and login functions. But we should add test for the issuance and presentation flow.

To make it less complicated we can use the API of the issuer and verifier so we do not need to jump between taps in playwright
